name: exploring workflow filters and Acyivities
on:
    workflow_dispatch: 
    push:
        branches: 
            - main
            - '!feature/*'  # ignoring pushing to any branch name starting with feature using !
    pull_request: 
        types: 
          - opened
          - closed
        paths-ignore: 
            - README.md # workflow will only run when a pull request taht includes a change on any file other than README.md
        branches: 
            - main  # configures your workflow to only run on pull requests that target specific branches.
jobs: 
    update-readme:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Render terraform docs and push changes
            uses: terraform-docs/gh-actions@v1.3.0 # Pinned version
            with:
              working-dir: .
              output-file: README.md
              output-method: inject
              git-push: "true"
              git-commit-message: "docs: automated terraform-docs update"
            
    #       - name: Genrate README content
    #         run: |
    #           echo "# Project Auto-Update" > README.md
    #           echo "Last updated on: $(date)" >> README.md
    #           echo "Triggered by event: ${{ github.event_name }}" >> README.md
    #           echo "Executed on: ubuntu-latest" >> README.md

    #       - name: Commit and Push changes
    #         run: |
    #           git config --global user.name "github-actions[bot]"
    #           git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #           git add README.md
    #           # Only commit if there are actual changes to avoid errors
    #           git diff --quiet && git diff --staged --quiet || (git commit -m "docs: auto-update README" && git push)
    # hello:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - run: echo this workflow/jobs/step is executed for event type - $ {{ github.event_name }}


